### ISSUE TITLE
Duplicate headers are erased

### ISSUE THREAD

**Issue by benmcderm** [maxthyen/table-scraper#5]
If I scrape a table on a page that has headers of the same name, it ignores the second header and doesn't include it in the scraped JSON object.

**Comment by maxthyen** [comment]
hey thanks for reporting, could you bump your version to 0.1.0 and try again? I haven't updated the repo due to some dependency issues but will eventually. 

If you're already using 0.1.0 and running into the same issue could you point me to the data source you're trying to scrape?

**Comment by benmcderm** [comment]
@maxthyen thanks for the quick response - the upgrade to 0.1.0 worked!  I was confused because tabletojson definitely supported that, should've checked npm first.  Cheers!

**Comment by maxthyen** [comment]
ok great! thank you. and yeah i added it here: https://github.com/iaincollins/tabletojson/pull/12 👍
